### ISSUE TITLE
Apdu with usb

### ISSUE THREAD

**Issue by redDwarf03** [ZeroPass/dmrtd#1]
Hello
I would like to send an APDU to a device with usb connection and not with nfc. Is it possible with your lib ?
Thx

**Comment by smlu** [comment]
Hey, sending APDU commands to USB communication interface is not supported (yet). For that you would have to implement [ComProvider](https://github.com/ZeroPass/dmrtd/blob/master/lib/src/com/com_provider.dart#L13-L28) to communicate with USB device.

After such interface is implemented it'd be easy to use it with e.g. ISO7816 class [ICC](https://github.com/ZeroPass/dmrtd/blob/master/lib/src/proto/iso7816/icc.dart#L25-L244) (if not reading biometric passports). For example:
```dart
var usbCom = UsbComProvider(...);
var icc = ICC(usbCom);
icc.selectFileByPath(...);
icc.readBinary(offset: 0, ne: ...);
```

Note, that the [_transceive](https://github.com/ZeroPass/dmrtd/blob/master/lib/src/proto/iso7816/icc.dart#L216-L229) method of class [ICC](https://github.com/ZeroPass/dmrtd/blob/master/lib/src/proto/iso7816/icc.dart#L25-L244) is private but I could make it public if you need to send raw APDU commands.

**Comment by redDwarf03** [comment]
Thx. I will try this and I will send you a feedback! That is for send commands to ledger key (https://www.ledger.com/)

**Comment by smlu** [comment]
@redDwarf03 fyi, the flutter NFC kit library is adding support for [WebUSB](https://github.com/nfcim/flutter_nfc_kit/tree/webusb_support).
