### ISSUE TITLE
Example doesn't build profile or release builds.

### ISSUE THREAD

**Issue by JanPel** [ZeroPass/dmrtd#11]
Was trying to build the example app. It works in debug mode, but when trying to run it in profile or release mode it shows the following error: 
```
Command RuleScriptExecution failed with a nonzero exit code
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It seems like it is a consequence of the flutter_nfc_kit dependency, but not 100% sure.

**Comment by smlu** [comment]
Does it compile in Xcode? There is sometimes issue with pods not correctly installing all required dependency. In such cases It's best to remove all cache or reset `ios` folder to initial setting. Another option is opening the project in xcode and fix missing dependency there.

Some info: https://github.com/flutter/flutter/issues/43591

**Comment by smlu** [comment]
Closing this issue since no further information was provided.
