### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by vunguyen2808** [ZeroPass/dmrtd#16]
Hello, after cloning I cannot run the project, can you help me? Please..

**Comment by duydai24** [comment]
Hello, I'm having the same problem as you, need developer support. Help me!

**Comment by smlu** [comment]
What is the issue? Are there any build errors?

**Comment by vunguyen2808** [comment]
> What is the issue? Are there any build errors?

Sorry for the late reply, I've run the project now but unfortunately I need to read Citizen ID Cards using NFC, but don't know if your source can read it, I'm having difficulty developing an application Use the NFC reader to retrieve the necessary DGs

**Comment by smlu** [comment]
Unfortunately I'm not familiar with Citizen ID. In general, if card supports [ICAO 9303](https://www.icao.int/publications/pages/publication.aspx?docnum=9303) MRTD standard and BAC protocol, you should be able to read it using this library.

**Comment by vunguyen2808** [comment]
> Unfortunately I'm not familiar with Citizen ID. In general, if card supports [ICAO 9303](https://www.icao.int/publications/pages/publication.aspx?docnum=9303) MRTD standard and BAC protocol, you should be able to read it using this library.

Thank you very much for your attention to my question. Have a good day.

**Comment by Kartali-Mohamed** [comment]
Please how you can run the project!!
