### ISSUE TITLE
Error: The method 'PlatformButton' isn't defined for the class

### ISSUE THREAD

**Issue by psimatis** [ZeroPass/dmrtd#17]
I get the following error. How do I fix it?

_lib/main.dart:563:29: Error: The method 'PlatformButton' isn't defined for the class '_MrtdHomePageState'.
 - '_MrtdHomePageState' is from 'package:nfc_passport_3/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlatformButton'.
                            PlatformButton( // btn Read MRTD
                            ^^^^^^^^^^^^^^_

Thanks!

**Comment by smlu** [comment]
The solution is to either pin version  of `flutter_platform_widgets` to 1.20 or use develop branch.

**Comment by psimatis** [comment]
Hi thanks for the response.

I simply renamed it to PlatformTextButton and it works
