### ISSUE TITLE
Parse data stored in dg7 

### ISSUE THREAD

**Issue by zamirszn** [ZeroPass/dmrtd#21]
From documentations I found online , it say mark or signature (digital version of hand written signature) are stored in dg7 data , I know it is optional in some documents , I'm trying to parse the imageData if its present just like in dg2

**Comment by smlu** [comment]
Due to lack of test data (no EF.DG07 public test data) there is no plan to support EF.DG07 file parsing atm.
We will gladly accept PR if anyone is willing to contribute code for it tho.

**Comment by zamirszn** [comment]
> Due to lack of test data (no EF.DG07 public test data) there is no plan to support EF.DG07 file parsing atm.
> We will gladly accept PR if anyone is willing to contribute code for it tho.

Ok thanks , I do have test data, but I have no idea on how to parse it , I guess I'll do more research , thanks alot

**Comment by smlu** [comment]
The specification for EF.DG7 can be found in ICAO 9303 Part 10, Section 4.7.7 ([https://www.icao.int/publications/documents/9303_p10_cons_en.pdf](https://www.icao.int/publications/documents/9303_p10_cons_en.pdf)). Note, that spec requires support for JFIF  and JPEG 2000 image format.
