### ISSUE TITLE
It dose not work with me for syrian passport

### ISSUE THREAD

**Issue by omarnasser199789** [ZeroPass/dmrtd#22]
I've made sure from passport number DOB and expiration date, but I still haven’t succeed 
in this code 
 final rapdu = await _transceive(
      CommandAPDU(cla: cla, ins: ISO7816_INS.EXTERNAL_AUTHENTICATE, p1: 0x00, p2: 0x00, data: data, ne: ne)
    );
     if(rapdu.status != StatusWord.success) {
      throw ICCError("External authenticate failed", rapdu.status, rapdu.data);
    }
    
    Always the status != StatusWord.success

**Comment by smlu** [comment]
What is the value of status code? Can you read your passport with any other passport reader app?

**Comment by omarnasser199789** [comment]
Yeah I can read it using ReadID app from app store
can you help me to fix this issue

**Comment by smlu** [comment]
What is the value od `rpdu.status`? 

Also, in the ReadID app, check what protocol was used to establish session with passport (BAC or PACE). If it says PACE then your passport might not support the BAC protocol. FYI, this library only supports the BAC proto. Implementation of PACE proto is in the works.

**Comment by smlu** [comment]
Closing this issue now, as no further info was provided.
