### ISSUE TITLE
The Protocol (step) Failed On Iphone 

### ISSUE THREAD

**Issue by tanvirsikdar05** [ZeroPass/dmrtd#37]
I use dmrtd for E-passport Scanning which work fine on android device and Iphone 12pro. But when i run Iphone 13 or 14 or 15 with same ios version (ios: 18)  i seen a error after tag passport : (The Protocol (step) Failed ).
I tested with Iphone 12pro BANGLADESHI passport BUT all fail come from South korean Passport

![imgpsh_fullsize_anim](https://github.com/user-attachments/assets/525e9f80-9f29-4337-9407-3c1c6dd46230)

i checked many time the BAC authentication Data is Correct and I declared all necessary permission and signing capability :

```
<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>A0000002471001</string>
		<string>E80704007F00070302</string>
		<string>A000000167455349474E</string>
		<string>A0000002480100</string>
		<string>A0000002480200</string>
		<string>A0000002480300</string>
		<string>A00000045645444C2D3031</string>
	</array>
	<key>NSNFCTagReadingCapability</key>
	<true/>
	<key>NFCReaderUsageDescription</key>
	<string>NFC tag to read E-passport </string>

<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>NFCISO7816</string>
	</array>

```

Here is my code:
```
startNfcScan(String documentNumber,String dob,String expireDate)async{
    var birth=await keyDateFormate(dob);
    var expire=await keyDateFormate(expireDate);
    AccessKey bacKeySeed = DBAKey( documentNumber,  DateTime.parse(birth), DateTime.parse(expire), paceMode: false);
    try {
      //re-set all
      _isReading = true;
      _isNfcCancalled = false;
      imageNfc =Uint8List(0);
      nfcScanStatus.value ='holdPassport'.tr;
      //nfcState.value ='tagging';
      try {
         await _nfc.connect(iosAlertMessage: 'holdPassport'.tr);
        final passport = Passport(_nfc);
        nfcScanStatus.value ='readingPassport'.tr;
        await _nfc.setIosAlertMessage('readingPassport'.tr ?? "Passport Data Reading..");
        //nfcState.value ='tagged';
        final mrtdData = MrtdData();
        try {
          mrtdData.cardAccess = await passport.readEfCardAccess();
        } on PassportError {
          //if (e.code != StatusWord.fileNotFound) rethrow;
        }
        // _nfc.setIosAlertMessage(formatProgressMsg('readingPassport'.tr ?? "df", 40));
        await passport.startSession(bacKeySeed as DBAKey);
        //nfcState.value ='scanning';
        // _nfc.setIosAlertMessage(formatProgressMsg('readingPassport'.tr ?? "df", 80));
        mrtdData.com = await passport.readEfCOM();
        if (mrtdData.com!.dgTags.contains(EfDG2.TAG)) {
          mrtdData.dg2 = await passport.readEfDG2();
        }
         //_nfc.setIosAlertMessage(formatProgressMsg('readingPassport'.tr ?? "D", 100));
        imageNfc = await extractImageBytes(mrtdData.dg2!.toBytes());
        print(imageNfc);
        //nfcState.value ='finished';
      } on Exception catch (e) {
        _isNfcCancalled=true;
        await _nfc.disconnect(iosErrorMessage: e.toString());
        nfcScanStatus.value="Cancelled";
      } finally {
        if(!_isNfcCancalled) await _nfc.disconnect(iosAlertMessage: "Finished");
        _isReading=false;
      }
    } on Exception catch (e) {
      print("nfc error$e");
    }

  }
```

**Comment by smlu** [comment]
Hey, this issue might be related to #36.
Is there any chance you could provide some logs?
Does it work on Android, if so could you also provide corresponding logs for comparison.
Also, what iOS version is the iPhone 12 Pro running in the successful passport scan case?

**Comment by tanvirsikdar05** [comment]
Thanks for replay .

yes its work well in android all scenario and work well my iphone 12pro ios version (18.1.1) ..the problem is when try to scan in iphone 14,15 with same ios version its show protocol step fail..
ahh ok i will show you logs

**Comment by smlu** [comment]
Looking some more into this issue and it might be related to https://github.com/ZeroPass/dmrtd/issues/28#issuecomment-2139734820. It is very unusual that it works on an older version of the iPhone but not on a newer one. And it just might have to do something with this new pooling option [NFCTagReaderSession.PollingOption.pace](https://developer.apple.com/documentation/corenfc/nfctagreadersession/pollingoption/3950980-pace).
I unfortunately don't have access to iPhone 14 and 15 atm to try replicating this issue.

**Comment by tanvirsikdar05** [comment]
thanks again for replay .
i have no iphone 13 or 14 thats why i cant collect logs .but i see after open ios NFC dialog its waiting for tag when passport tagged its received error immediately something like wrong BAC key

**Comment by smlu** [comment]
How do you make tests then for iPhone 13, 14 and 15?
Also, is scanned passport(s) the same when testing app between devices?

**Comment by tanvirsikdar05** [comment]
Hi Now i dont see previous error but i got this error both platform 

`NfcProviderError: PlatformException(500, Communication error, Tag was lost., null)`

**Comment by smlu** [comment]
@tanvirsikdar05 Were you able to resolve this issue?
